Repository ISIS3510-202410-Team23/SwiftApp, pull requests merged in 2024-03, with the labels that each got.

#30 [FIX] Apply singleton pattern to Firebase Client
  FoodBookApp/DAO/Firebase/ExampleDAOFirebase.swift
  FoodBookApp/Persitence/Firebase.swift
Labels: fix

#46 [FEATURE] Fetch Categories from Backend
  FoodBookApp.xcodeproj/project.pbxproj
  FoodBookApp/DAO/CategoryDAO.swift
  FoodBookApp/DAO/Firebase/CategoryDAOFirebase.swift
  FoodBookApp/Repositories/Category/CategoryRepository.swift
  FoodBookApp/Repositories/Category/CategoryRepositoryImpl.swift
  FoodBookApp/UI/Views/CreateReview/CreateReview1ViewModel.swift
Labels: enhancement

#44 [FEATURE] Fetch all spots and calculate distance
  FoodBookApp.xcodeproj/project.pbxproj
  FoodBookApp.xcodeproj/project.xcworkspace/xcuserdata/juan.xcuserdatad/UserInterfaceState.xcuserstate
  FoodBookApp/ContentView.swift
  FoodBookApp/DAO/Firebase/SpotDAOFirebase.swift
  FoodBookApp/DAO/SpotDAO.swift
  FoodBookApp/Models/Spot.swift
  FoodBookApp/Repositories/Spot/SpotRepository.swift
  FoodBookApp/Repositories/Spot/SpotRepositoryImpl.swift
  FoodBookApp/Services/BackendService.swift
  FoodBookApp/Services/LocationService.swift
  FoodBookApp/UI/Components/SpotCard.swift
  FoodBookApp/UI/Views/Browse/BrowseView.swift
  FoodBookApp/UI/Views/Browse/BrowseViewModel.swift
  FoodBookApp/UI/Views/ForYou/ForYouView.swift
  FoodBookApp/UI/Views/ForYou/ForYouViewModel.swift
  FoodBookApp/UI/Views/LoginView.swift
  FoodBookApp/UI/Views/SpotDetail/SpotDetailView.swift
  FoodBookApp/Utils/LocationUtils.swift
Labels: enhancement

#45 [FEATURE] Context Aware Feature
  FoodBookApp.xcodeproj/project.pbxproj
  FoodBookApp/ContentView.swift
  FoodBookApp/FoodBookApp.swift
  FoodBookApp/Handlers/NotificationHandler.swift
  FoodBookApp/Info.plist
  FoodBookApp/Services/LocationService.swift
  FoodBookApp/Utils/Utils.swift
Labels: enhancement

#52 [BUGFIX] Multiple bug fixes, see description
  FoodBookApp.xcodeproj/project.pbxproj
  FoodBookApp.xcodeproj/project.xcworkspace/xcuserdata/juan.xcuserdatad/UserInterfaceState.xcuserstate
  FoodBookApp/Persistence/Firebase.swift
  FoodBookApp/UI/Views/Bookmarks/BookmarksView.swift
  FoodBookApp/UI/Views/ContentView.swift
  FoodBookApp/UI/Views/CreateReview/CreateReview1View.swift
  FoodBookApp/UI/Views/CreateReview/CreateReview2ViewModel.swift
  FoodBookApp/UI/Views/ForYou/ForYouView.swift
  FoodBookApp/UI/Views/ForYou/ForYouViewModel.swift
  FoodBookApp/UI/Views/Login/LoginView.swift
  FoodBookApp/UI/Views/Login/LoginViewModel.swift
  FoodBookApp/Utils/Utils.swift
Labels: bug

#53 [FIX] Refactor of spotId, notification and category lowercase
  FoodBookApp.xcodeproj/project.xcworkspace/xcuserdata/laura.xcuserdatad/UserInterfaceState.xcuserstate
  FoodBookApp/Handlers/NotificationHandler.swift
  FoodBookApp/UI/Views/CreateReview/CreateReview1View.swift
  FoodBookApp/UI/Views/CreateReview/CreateReview2View.swift
  FoodBookApp/UI/Views/SpotDetail/SpotDetailView.swift
Labels: fix
