Repository ISIS3510-202410-Team23/SwiftApp, pull requests merged in 2024-05, with the labels that each got.

#149 [FIX] Bug related to login cover not being presented
  FoodBookApp/FoodBookApp.swift
  FoodBookApp/UI/Views/Content/ContentView.swift
  FoodBookApp/UI/Views/RootView.swift
  FoodBookApp/UI/Views/User/UserView.swift
Labels: bug

#146 [FEATURE] Category sorting multithreading
  FoodBookApp/Utils/Utils.swift
Labels: enhancement

#157 [FIX] More descriptive message when user has bookmarks but data cannot be fetched
  FoodBookApp/UI/Views/Bookmarks/BookmarksView.swift
Labels: fix

#158 [BUGFIX] EC reviews uploaded twice
  FoodBookApp/UI/Components/SpotCard.swift
  FoodBookApp/UI/Views/Bookmarks/BookmarksView.swift
  FoodBookApp/UI/Views/ForYou/ForYouView.swift
  FoodBookApp/Utils/Utils.swift
Labels: bug

#159 [FIX] Upload search terms to firebase
  FoodBookApp.xcodeproj/project.pbxproj
  FoodBookApp/Repositories/SearchUsage/SearchUsageRepository.swift
  FoodBookApp/Repositories/SearchUsage/SearchUsageRepositoryImpl.swift
  FoodBookApp/ServiceAdapter/Firebase/SearchUsageSAFirebase.swift
  FoodBookApp/ServiceAdapter/SearchUsageSA.swift
  FoodBookApp/UI/Views/Content/ContentView.swift
  FoodBookApp/UI/Views/Content/ContentViewModel.swift
  FoodBookApp/UI/Views/User/UserView.swift
  FoodBookApp/UI/Views/User/UserViewModel.swift
Labels: fix

#172 [PATCH] Fetching is done also when leaving login view
  FoodBookApp/Services/AuthService.swift
  FoodBookApp/UI/Views/Content/ContentView.swift
  FoodBookApp/UI/Views/Content/ContentViewModel.swift
Labels: bug

#174 [FIX] Notification permission timing
  FoodBookApp/FoodBookApp.swift
  FoodBookApp/Handlers/NotificationHandler.swift
  FoodBookApp/UI/Views/Login/LoginView.swift
Labels: fix

#177 [PATCH] Minor: restore progress view
  FoodBookApp/UI/Views/Browse/BrowseView.swift
  FoodBookApp/UI/Views/Content/ContentView.swift
  FoodBookApp/UI/Views/Content/ContentViewModel.swift
  FoodBookApp/UI/Views/User/UserViewModel.swift
Labels: bug

#180 [FIX] Categories sorting function
  FoodBookApp/Utils/Utils.swift
Labels: fix

#182 [PATCH] Reverts sorting function to previous version
  FoodBookApp/Utils/Utils.swift
Labels: bug

#183 [FEATURE] Easier keyboard access for create review views
  FoodBookApp/UI/Views/CreateReview/CreateReview1View.swift
  FoodBookApp/UI/Views/CreateReview/CreateReview2View.swift
Labels: enhancement

#186 [PATCH] EC reviews uploaded twice (v2)
  FoodBookApp/SQLite/DBManager.swift
  FoodBookApp/UI/Views/Bookmarks/BookmarksView.swift
  FoodBookApp/UI/Views/Browse/BrowseView.swift
  FoodBookApp/UI/Views/Content/ContentView.swift
  FoodBookApp/UI/Views/ForYou/ForYouView.swift
Labels: bug

#171 [FEATURE] Spot detail fetching time BQ
  FoodBookApp.xcodeproj/project.pbxproj
  FoodBookApp/Repositories/SpotDetailFetchingTime/SpotDetailFetchingTimeImpl.swift
  FoodBookApp/Repositories/SpotDetailFetchingTime/SpotDetailFetchingTimeRepository.swift
  FoodBookApp/SQLite/DBManager.swift
  FoodBookApp/ServiceAdapter/Firebase/SpotDetailFetchingTimeSAFirebase.swift
  FoodBookApp/ServiceAdapter/SpotDetailFetchingTimeSA.swift
  FoodBookApp/UI/Views/SpotDetail/SpotDetailView.swift
  FoodBookApp/UI/Views/SpotDetail/SpotDetailViewModel.swift
Labels: enhancement

#189 [FIX] Changes requested in viva voce
  FoodBookApp/UI/Components/SpotCard.swift
  FoodBookApp/UI/Views/Bookmarks/BookmarksView.swift
  FoodBookApp/UI/Views/CreateReview/CreateReview2View.swift
  FoodBookApp/UI/Views/ForYou/ForYouView.swift
  FoodBookApp/UI/Views/SpotDetail/SpotDetailView.swift
  FoodBookApp/UI/Views/User/UserView.swift
Labels: bug, enhancement, fix

#190 [FEATURE] Review Reporting
  FoodBookApp.xcodeproj/project.pbxproj
  FoodBookApp/Repositories/Review/ReviewRepository.swift
  FoodBookApp/Repositories/Review/ReviewRepositoryImpl.swift
  FoodBookApp/ServiceAdapter/Firebase/ReviewSAFirebase.swift
  FoodBookApp/ServiceAdapter/ReviewSA.swift
  FoodBookApp/UI/Components/TextFieldWithLimit.swift
  FoodBookApp/UI/Views/ReviewReport/ReportReviewView.swift
  FoodBookApp/UI/Views/ReviewReport/ReviewReportViewModel.swift
  FoodBookApp/UI/Views/SpotDetail/ReviewsView.swift
  FoodBookApp/UI/Views/SpotDetail/SpotDetailView.swift
Labels: enhancement

#188 [FEATURE] Settings view
  FoodBookApp.xcodeproj/project.pbxproj
  FoodBookApp/Handlers/NotificationHandler.swift
  FoodBookApp/UI/Views/Content/ContentView.swift
  FoodBookApp/UI/Views/CreateReview/CreateReview2View.swift
  FoodBookApp/UI/Views/Settings/SettingsView.swift
Labels: enhancement

#194 [FIX] Remove debug buttons
  FoodBookApp/UI/Views/User/UserView.swift
Labels: fix

#198 [FEATURE] Image caching
  FoodBookApp.xcodeproj/project.pbxproj
  FoodBookApp/UI/Components/SpotCard.swift
  FoodBookApp/UI/Views/User/UserView.swift
Labels: enhancement, fix

#193 [FEATURE] User reviews view using caching
  FoodBookApp.xcodeproj/project.pbxproj
  FoodBookApp/Repositories/Review/ReviewRepository.swift
  FoodBookApp/Repositories/Review/ReviewRepositoryImpl.swift
  FoodBookApp/ServiceAdapter/Firebase/ReviewSAFirebase.swift
  FoodBookApp/ServiceAdapter/ReviewSA.swift
  FoodBookApp/Services/AuthService.swift
  FoodBookApp/Services/CacheService.swift
  FoodBookApp/UI/Components/ReviewCard.swift
  FoodBookApp/UI/Views/ReviewReport/ReportReviewView.swift
  FoodBookApp/UI/Views/Reviews/ReviewsView.swift
  FoodBookApp/UI/Views/Reviews/ReviewsViewModel.swift
  FoodBookApp/UI/Views/SpotDetail/ReviewsView.swift
  FoodBookApp/UI/Views/User/UserView.swift
  FoodBookApp/UI/Views/User/UserViewModel.swift
  FoodBookApp/UI/Views/UserReviews/UserReviewsView.swift
  FoodBookApp/UI/Views/UserReviews/UserReviewsViewModel.swift
Labels: enhancement

#191 [FEATURE] Bug reporting
  FoodBookApp.xcodeproj/project.pbxproj
  FoodBookApp/Models/BugReport.swift
  FoodBookApp/Models/BugReportDraft.swift
  FoodBookApp/Repositories/BugReport/BugReportRepository.swift
  FoodBookApp/Repositories/BugReport/BugReportRepositoryImpl.swift
  FoodBookApp/SQLite/DBManager.swift
  FoodBookApp/ServiceAdapter/BugReportSA.swift
  FoodBookApp/ServiceAdapter/Firebase/BugReportSAFirebase.swift
  FoodBookApp/UI/Components/SpotCard.swift
  FoodBookApp/UI/Views/Bookmarks/BookmarksView.swift
  FoodBookApp/UI/Views/BugReport/BugReportView.swift
  FoodBookApp/UI/Views/BugReport/BugReportViewModel.swift
  FoodBookApp/UI/Views/Content/ContentView.swift
  FoodBookApp/UI/Views/Settings/SettingsView.swift
Labels: enhancement

#192 [FEATURE] Hot categories with caching strategy
  FoodBookApp/FoodBookApp.swift
  FoodBookApp/Services/BackendService.swift
  FoodBookApp/Services/CacheService.swift
  FoodBookApp/UI/Components/HCategoryList.swift
  FoodBookApp/UI/Components/SpotCard.swift
  FoodBookApp/UI/Views/Browse/BrowseView.swift
  FoodBookApp/UI/Views/Content/ContentView.swift
  FoodBookApp/UI/Views/Content/ContentViewModel.swift
Labels: enhancement

#200 [FIX] EC and other standarizaitons
  FoodBookApp/UI/Views/Browse/BrowseView.swift
  FoodBookApp/UI/Views/BugReport/BugReportView.swift
  FoodBookApp/UI/Views/ReviewReport/ReportReviewView.swift
  FoodBookApp/UI/Views/UserReviews/UserReviewsView.swift
  FoodBookApp/UI/Views/UserReviews/UserReviewsViewModel.swift
Labels: fix

#204 [FIX] M.O. (most) ForEach loops are now indexed
  FoodBookApp/UI/Components/HCategoryList.swift
  FoodBookApp/UI/Components/ReviewCard.swift
  FoodBookApp/UI/Views/Bookmarks/BookmarksView.swift
  FoodBookApp/UI/Views/Browse/BrowseView.swift
  FoodBookApp/UI/Views/BugReport/BugReportView.swift
  FoodBookApp/UI/Views/CreateReview/CreateReview1View.swift
  FoodBookApp/UI/Views/CreateReview/CreateReview2View.swift
  FoodBookApp/UI/Views/ForYou/ForYouView.swift
  FoodBookApp/UI/Views/Reviews/ReviewsView.swift
  FoodBookApp/UI/Views/SpotDetail/SpotDetailView.swift
  FoodBookApp/UI/Views/UserReviews/UserReviewsView.swift
Labels: fix

#202 [FIX] Separate `getUserReview()` logic
  FoodBookApp/ServiceAdapter/Firebase/ReviewSAFirebase.swift
Labels: fix
