Repository ISIS3510-202410-Team23/SwiftApp, pull requests merged in 2024-04, with the labels that each got.

#77 [FIX] Refactor DAO naming to SA
  FoodBookApp.xcodeproj/project.pbxproj
  FoodBookApp/Repositories/Category/CategoryRepositoryImpl.swift
  FoodBookApp/Repositories/Review/ReviewRepository.swift
  FoodBookApp/Repositories/Review/ReviewRepositoryImpl.swift
  FoodBookApp/Repositories/Spot/SpotRepository.swift
  FoodBookApp/Repositories/Spot/SpotRepositoryImpl.swift
  FoodBookApp/ServiceAdapter/CategorySA.swift
  FoodBookApp/ServiceAdapter/Firebase/CategorySAFirebase.swift
  FoodBookApp/ServiceAdapter/Firebase/ReviewSAFirebase.swift
  FoodBookApp/ServiceAdapter/Firebase/SpotSAFirebase.swift
  FoodBookApp/ServiceAdapter/ReviewSA.swift
  FoodBookApp/ServiceAdapter/SpotSA.swift
Labels: refactor

#80 [FIX] Show number of reviews in 'See more'
  FoodBookApp/UI/Views/SpotDetail/SpotDetailView.swift
Labels: fix

#76 [FU] adds local authentication to bookmarks
  FoodBookApp/Info.plist
  FoodBookApp/Services/AuthService.swift
  FoodBookApp/UI/Views/Bookmarks/BookmarksView.swift
Labels: enhancement

#83 [FEATURE] Eventual connectivity message when no hits in search
  FoodBookApp/UI/Views/Browse/BrowseView.swift
Labels: enhancement

#82 [FIX] Update UI to show category aggregation and top only top categories in browse.
  FoodBookApp/Models/Spot.swift
  FoodBookApp/UI/Components/HCategoryList.swift
  FoodBookApp/UI/Components/SpotCard.swift
  FoodBookApp/UI/Views/Browse/BrowseView.swift
  FoodBookApp/UI/Views/SpotDetail/SpotDetailView.swift
  FoodBookApp/Utils/Utils.swift
Labels: fix

#97 [FEATURE] Local database for review drafts
  FoodBookApp.xcodeproj/project.pbxproj
  FoodBookApp/Models/ReviewDraft.swift
  FoodBookApp/SQLite/DBManager.swift
  FoodBookApp/UI/Views/Bookmarks/BookmarksView.swift
  FoodBookApp/UI/Views/CreateReview/CreateReview1View.swift
  FoodBookApp/UI/Views/CreateReview/CreateReview2View.swift
  FoodBookApp/UI/Views/SpotDetail/SpotDetailView.swift
Labels: enhancement

#102 [FEATURE] Save a local copy of the image to file storage
  FoodBookApp/Models/ReviewDraft.swift
  FoodBookApp/SQLite/DBManager.swift
  FoodBookApp/UI/Views/CreateReview/CreateReview1View.swift
  FoodBookApp/UI/Views/CreateReview/CreateReview2View.swift
  FoodBookApp/UI/Views/User/UserView.swift
Labels: enhancement

#104 [FIX] Spinning wheel when loading spot detail
  FoodBookApp/UI/Views/SpotDetail/SpotDetailView.swift
Labels: fix

#107 [FIX] Draft can be created with just the image
  FoodBookApp/UI/Views/CreateReview/CreateReview1View.swift
Labels: fix

#108 [FEATURE] Unfinished reviews BQ + SQLite package
  FoodBookApp.xcodeproj/project.pbxproj
  FoodBookApp/Repositories/UnfinishedReview/UnfinishedReviewImpl.swift
  FoodBookApp/Repositories/UnfinishedReview/UnfinishedReviewRepository.swift
  FoodBookApp/ServiceAdapter/Firebase/UnfinishedReviewSAFirebase.swift
  FoodBookApp/ServiceAdapter/UnfinishedReviewSA.swift
  FoodBookApp/UI/Views/CreateReview/CreateReview1View.swift
  FoodBookApp/UI/Views/CreateReview/CreateReview1ViewModel.swift
  FoodBookApp/UI/Views/CreateReview/CreateReview2View.swift
  FoodBookApp/UI/Views/SpotDetail/SpotDetailView.swift
  SQLite.xcodeproj/project.pbxproj
  SQLite.xcodeproj/xcshareddata/xcschemes/SQLite Mac.xcscheme
  SQLite.xcodeproj/xcshareddata/xcschemes/SQLite iOS.xcscheme
  SQLite.xcodeproj/xcshareddata/xcschemes/SQLite tvOS.xcscheme
  SQLite.xcodeproj/xcshareddata/xcschemes/SQLite visionOS.xcscheme
  SQLite.xcodeproj/xcshareddata/xcschemes/SQLite watchOS.xcscheme
Labels: enhancement, good first issue

#111 [FIX] Fetch categories when fetching spot
  FoodBookApp/UI/Views/CreateReview/CreateReview1View.swift
  FoodBookApp/UI/Views/CreateReview/CreateReview1ViewModel.swift
  FoodBookApp/UI/Views/SpotDetail/SpotDetailView.swift
  FoodBookApp/UI/Views/SpotDetail/SpotDetailViewModel.swift
Labels: fix

#119 [FEATURE] Bookmarks BQ
  FoodBookApp.xcodeproj/project.pbxproj
  FoodBookApp/Repositories/BookmarksUsage/BookmarksUsageRepository.swift
  FoodBookApp/Repositories/BookmarksUsage/BookmarksUsageRepositoryImpl.swift
  FoodBookApp/ServiceAdapter/BookmarksUsageSA.swift
  FoodBookApp/ServiceAdapter/Firebase/BookmarksUsageSAFirebase.swift
  FoodBookApp/Services/BookmarksService.swift
Labels: enhancement

#126 [FEATURE] Eventual connectivity for review upload
  FoodBookApp/Handlers/NotificationHandler.swift
  FoodBookApp/Models/ReviewDraft.swift
  FoodBookApp/SQLite/DBManager.swift
  FoodBookApp/UI/Views/Browse/BrowseView.swift
  FoodBookApp/UI/Views/CreateReview/CreateReview1View.swift
  FoodBookApp/UI/Views/CreateReview/CreateReview2View.swift
  FoodBookApp/UI/Views/CreateReview/CreateReview2ViewModel.swift
  FoodBookApp/UI/Views/SpotDetail/SpotDetailView.swift
  FoodBookApp/UI/Views/User/UserView.swift
  FoodBookApp/Utils/Utils.swift
Labels: enhancement

#129 [REFACTOR] Missing commits
  FoodBookApp/SQLite/DBManager.swift
  FoodBookApp/UI/Views/SpotDetail/SpotDetailView.swift
Labels: refactor

#128 [FEATURE] Add timeout to login flow (once in the browser) using multi-threading
  FoodBookApp/UI/Views/Login/LoginView.swift
  FoodBookApp/UI/Views/Login/LoginViewModel.swift
  FoodBookApp/Utils/SignInGoogleHelper.swift
Labels: enhancement

#127 [FEATURE] Search history
  FoodBookApp/UI/Views/Content/ContentView.swift
  FoodBookApp/UI/Views/RootView.swift
  FoodBookApp/UI/Views/User/UserView.swift
Labels: enhancement

#133 [FEATURE] Preloaded restaurants cache
  FoodBookApp.xcodeproj/project.pbxproj
  FoodBookApp/Models/Cache/HardcodedSpots.swift
  FoodBookApp/UI/Views/Content/ContentViewModel.swift
Labels: enhancement

#135 [FEATURE] EC: spot detail, reviews and leave review + cache fix
  FoodBookApp/Models/Cache/HardcodedSpots.swift
  FoodBookApp/UI/Views/Content/ContentViewModel.swift
  FoodBookApp/UI/Views/SpotDetail/SpotDetailView.swift
Labels: enhancement

#140 [FEATURE] adds EC message for unavailable network and cache in FYP
  FoodBookApp/UI/Views/Content/ContentViewModel.swift
  FoodBookApp/UI/Views/ForYou/ForYouView.swift
Labels: fix
